version: '3'

services:
  nodeservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:10
    container_name: nodeservice
    restart: unless-stopped
    networks:
      - nodeservice-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=8080
      - DATABASE_HOST=mysqlservice
      - DATABASE_USER=root
      - DATABASE_PASS=root
      - DATABASE_PORT=3306
      - DATABASE=campy
    depends_on:
      - mysqlservice
      - redisservice
    links:
      - mysqlservice

  webserverservice:
    image: nginx:mainline-alpine
    container_name: webserverservice
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodeservice
    networks:
      - nodeservice-network

  mysqlservice:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ceos"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - nodeservice-network

  redisservice:
    image: redis
    container_name: redisservice
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    networks: 
      - nodeservice-network

volumes:
  web-root:
    driver: local
  data:
    driver: local

networks:
  nodeservice-network:
    driver: bridge